# permissions for end users to edit projectnetworkpolicytemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectnetworkpolicytemplate-editor-role
rules:
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectnetworkpolicytemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectnetworkpolicytemplates/status
  verbs:
  - get
