# permissions for end users to edit projectroletemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectroletemplate-editor-role
rules:
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectroletemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectroletemplates/status
  verbs:
  - get
