# permissions for end users to edit projectnetworkpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectnetworkpolicy-editor-role
rules:
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectnetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectnetworkpolicies/status
  verbs:
  - get
