# permissions for end users to edit projectroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectrole-editor-role
rules:
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectroles/status
  verbs:
  - get
