# permissions for end users to edit projectaccesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectaccess-editor-role
rules:
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectaccesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectaccesses/status
  verbs:
  - get
