# permissions for end users to view projectnetworkpolicytemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectnetworkpolicytemplate-viewer-role
rules:
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectnetworkpolicytemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectnetworkpolicytemplates/status
  verbs:
  - get
