# permissions for end users to view projectaccesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectaccess-viewer-role
rules:
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectaccesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectaccesses/status
  verbs:
  - get
