# permissions for end users to view projectnetworkpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectnetworkpolicy-viewer-role
rules:
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectnetworkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectnetworkpolicies/status
  verbs:
  - get
