apiVersion: project.djkormo.github.io/v1alpha1
kind: Project
metadata:
  name: project-sample-1
  namespace: project-operator
  labels:
    app: project-sample-label-1
    project-operator/pauseReconciliation: "false"
  annotations:
    "co.elastic.logs/multiline.type": "true"
    "co.elastic.logs/multiline.pattern": "true"
    "co.elastic.logs/multiline.negate": "true"
    "co.elastic.logs/multiline.match": "true"
spec:
# resourceQuota
  resourceQuota:
    hard: 
      requests.cpu: "2"
      requests.memory: 3Gi
      requests.ephemeral-storage: 1Gi
      limits.cpu: "4"
      limits.memory: 5Gi
      limits.ephemeral-storage: 2Gi
  # limitRange  
  limitRange:
    limits:
    - max:
        memory: "30G"
        cpu: "30"
      min:
        cpu: "50m"
        memory: "50Mi"
      default:
        cpu: "200m"
        memory: "200Mi"
        ephemeral-storage: "2Mi"
      defaultRequest:
        cpu: "100m"
        memory: "100Mi"
        ephemeral-storage: "1Mi"
      type: Container

