apiVersion: project.djkormo.github.io/v1alpha1
kind: ProjectNetworkPolicy
metadata:
  name: projectnetpol-default
  labels:
    app: project-default
    project-operator/pauseReconciliation: "false"
  annotations:
    "co.elastic.logs/multiline.type": "true"
    "co.elastic.logs/multiline.pattern": "true"
    "co.elastic.logs/multiline.negate": "true"
    "co.elastic.logs/multiline.match": "true"
spec:
  projectName: default
  networkPolicies:
    - projectnetpoltemplate-allow-dns
    - projectnetpoltemplate-deny-ingress
