apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: project-operator-manager-role
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projects/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: project-operator-manager-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - limitranges
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# Operator CRD
# Projects 
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# ProjectNetworkPolicyTemplates  
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectnetworkpolicytemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectnetworkpolicytemplates/finalizers
  verbs:
  - update
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectnetworkpolicytemplates/status
  verbs:
  - get
  - list
  - patch
  - update  
# ProjectNetworkPolicies   
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectnetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectnetworkpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectnetworkpolicies/status
  verbs:
  - get
  - list
  - patch
  - update
# ProjectRoletemplates projectroletemplates
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectroletemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectroletemplates/finalizers
  verbs:
  - update
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectroletemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch  
# ProjectRoles  
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectroles/finalizers
  verbs:
  - update
- apiGroups:
  - project.djkormo.github.io
  resources:
  - projectroles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  - authorization.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: project-operator-manager-rolebinding
  labels:
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: project-operator-controller-manager
  namespace: {{  .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-operator-manager-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "chart.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: project-operator-controller-manager
  namespace: {{  .Release.Namespace }}